# Generated by Django 6.0.2 on 2026-03-01 06:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(help_text="Visitor's full name as submitted.", max_length=100)),
                ('email', models.EmailField(help_text="Visitor's reply-to email address.", max_length=254)),
                ('subject', models.CharField(help_text='Short subject line describing the inquiry.', max_length=200)),
                ('message', models.TextField(help_text='Full message body from the visitor.')),
                ('is_read', models.BooleanField(default=False, help_text='Mark as read once reviewed. Managed in Django Admin.')),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(help_text='Full display name shown on the portfolio.', max_length=100)),
                ('tagline', models.CharField(blank=True, help_text='Short one-liner shown under your name. Max 160 chars.', max_length=160)),
                ('bio', models.TextField(help_text='Longer description. Markdown supported on the frontend.')),
                ('avatar', models.ImageField(help_text='Profile picture. Recommended: square, min 400×400px.', upload_to='core/avatars/')),
                ('resume', models.FileField(blank=True, help_text='PDF resume. Served from MEDIA_ROOT in dev, nginx in prod.', upload_to='core/resumes/')),
                ('role', models.CharField(help_text="Job title e.g. 'Backend Engineer'.", max_length=100)),
                ('email', models.EmailField(help_text='Public contact email displayed on the portfolio.', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Optional contact phone number.', max_length=20)),
                ('location', models.CharField(blank=True, help_text="City/country string e.g. 'Kathmandu, Nepal'.", max_length=100)),
                ('is_available', models.BooleanField(default=False, help_text="Toggles the 'open to work' indicator on the frontend.")),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('devto', 'Dev.to'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('website', 'Personal Website')], help_text='Social platform identifier.', max_length=20)),
                ('url', models.URLField(help_text="Full URL to the owner's profile on this platform.")),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this link from the frontend without deleting it.')),
                ('profile', models.ForeignKey(help_text='Portfolio owner this link belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.profile')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['platform'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'platform'), name='unique_platform_per_profile')],
            },
        ),
    ]
