# Generated by Django 6.0.2 on 2026-03-01 08:44

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Rich-text biography. Supports formatting, links, lists.'),
        ),
    ]
