# Generated by Django 6.0.2 on 2026-03-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('devto', 'Dev.to'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('website', 'Personal Website'), ('medium', 'medium')], help_text='Social platform identifier.', max_length=20),
        ),
    ]
