# Generated by Django 6.0.2 on 2026-03-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bijay_dev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techstack',
            name='icon_cdn',
            field=models.URLField(blank=True, help_text='Optional CDN URL for icon image when no file is uploaded.'),
        ),
    ]
