# Generated by Django 6.0.2 on 2026-03-13 10:19

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bijay_dev', '0002_techstack_icon_cdn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Optional rich-text notes, achievements, or academic highlights.'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Rich-text responsibilities and achievements. Supports links and lists.'),
        ),
    ]
